name: Java CI with Maven

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - 'release/**'
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - 'release/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Variables to be used in the workflow
    env:
      MAVEN_CACHE_FOLDER: ${{ github.workspace }}/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=${{ github.workspace }}/.m2/repository'

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout repository
      uses: actions/checkout@v3

    # Caches Maven dependencies to speed up the build process
    - name: Cache Maven local repo
      uses: actions/cache@v3
      with:
        path: ${{ env.MAVEN_CACHE_FOLDER }}
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    # Runs Maven commands to build and test the project
    - name: Build with Maven
      run: mvn -X -B verify -Dmaven.repo.local=${{ env.MAVEN_CACHE_FOLDER }}
